// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = {
  [KeyType in keyof T]: T[KeyType];
};
/** Content for 404 documents */
interface _404DocumentData {
  /**
   * Slice Zone field in *404*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: 404.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/slices
   *
   */
  slices: prismic.SliceZone<_404DocumentDataSlicesSlice>;
  /**
   * Meta Description field in *404*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: 404.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  meta_description: prismic.RichTextField;
  /**
   * Meta Image field in *404*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: 404.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/core-concepts/image
   *
   */
  meta_image: prismic.ImageField<never>;
  /**
   * Meta Title field in *404*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: 404.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  meta_title: prismic.KeyTextField;
}
/**
 * Slice for *404 → Slice Zone*
 *
 */
type _404DocumentDataSlicesSlice = ErrorSlice;
/**
 * 404 document from Prismic
 *
 * - **API ID**: `404`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type _404Document<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<_404DocumentData>, "404", Lang>;
/** Content for Contacts documents */
interface ContactsDocumentData {
  /**
   * Headline field in *Contacts*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contacts.headline
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  headline: prismic.RichTextField;
  /**
   * Name field in *Contacts*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contacts.name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  name: prismic.RichTextField;
  /**
   * Link field in *Contacts*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: contacts.link
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
   *
   */
  link: prismic.LinkField;
}
/**
 * Contacts document from Prismic
 *
 * - **API ID**: `contacts`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ContactsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<ContactsDocumentData>,
    "contacts",
    Lang
  >;
/** Content for Homepage documents */
interface HomepageDocumentData {
  /**
   * Slice Zone field in *Homepage*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/slices
   *
   */
  slices: prismic.SliceZone<HomepageDocumentDataSlicesSlice>;
  /**
   * Meta Description field in *Homepage*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: homepage.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  meta_description: prismic.RichTextField;
  /**
   * Meta Image field in *Homepage*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/core-concepts/image
   *
   */
  meta_image: prismic.ImageField<never>;
  /**
   * Meta Title field in *Homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: homepage.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  meta_title: prismic.KeyTextField;
}
/**
 * Slice for *Homepage → Slice Zone*
 *
 */
type HomepageDocumentDataSlicesSlice = MarqueeSlice | HeroHomepageSlice;
/**
 * Homepage document from Prismic
 *
 * - **API ID**: `homepage`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomepageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<HomepageDocumentData>,
    "homepage",
    Lang
  >;
/** Content for Navigation documents */
interface NavigationDocumentData {
  /**
   * Logo field in *Navigation*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation.logo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  logo: prismic.RichTextField;
  /**
   * Logo Link field in *Navigation*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation.logo_link
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
   *
   */
  logo_link: prismic.LinkField;
  /**
   * Slice Zone field in *Navigation*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/slices
   *
   */
  slices: prismic.SliceZone<NavigationDocumentDataSlicesSlice>;
}
/**
 * Slice for *Navigation → Slice Zone*
 *
 */
type NavigationDocumentDataSlicesSlice =
  | NavigationItemSlice
  | NavigationSocialMediaLinksSlice;
/**
 * Navigation document from Prismic
 *
 * - **API ID**: `navigation`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type NavigationDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<NavigationDocumentData>,
    "navigation",
    Lang
  >;
/** Content for Page documents */
interface PageDocumentData {
  /**
   * Slice Zone field in *Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/slices
   *
   */
  slices: prismic.SliceZone<PageDocumentDataSlicesSlice>;
  /**
   * Meta Description field in *Page*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  meta_description: prismic.RichTextField;
  /**
   * Meta Image field in *Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/core-concepts/image
   *
   */
  meta_image: prismic.ImageField<never>;
  /**
   * Meta Title field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  meta_title: prismic.KeyTextField;
}
/**
 * Slice for *Page → Slice Zone*
 *
 */
type PageDocumentDataSlicesSlice = ResumeSlice | MarqueeSlice;
/**
 * Page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<PageDocumentData>, "page", Lang>;
/** Content for Preloader documents */
interface PreloaderDocumentData {
  /**
   * Description field in *Preloader*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: preloader.description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  description: prismic.RichTextField;
  /**
   * Image field in *Preloader*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: preloader.image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/image
   *
   */
  image: prismic.ImageField<never>;
  /**
   * Button Label field in *Preloader*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: preloader.button_label
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  button_label: prismic.RichTextField;
}
/**
 * Preloader document from Prismic
 *
 * - **API ID**: `preloader`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PreloaderDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<PreloaderDocumentData>,
    "preloader",
    Lang
  >;
/** Content for Project documents */
interface ProjectDocumentData {
  /**
   * Project Name field in *Project*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: project.project_name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  project_name: prismic.RichTextField;
  /**
   * Project Year field in *Project*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: This text is only used on the about page
   * - **API ID Path**: project.project_year
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  project_year: prismic.RichTextField;
  /**
   * Project Description field in *Project*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: This text is only used on the about page
   * - **API ID Path**: project.project_description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  project_description: prismic.RichTextField;
  /**
   * Content field in *Project*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: project.content[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/group
   *
   */
  content: prismic.GroupField<Simplify<ProjectDocumentDataContentItem>>;
  /**
   * Project URL field in *Project*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: project.project_url
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
   *
   */
  project_url: prismic.LinkField;
  /**
   * Project Image field in *Project*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: project.project_image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/image
   *
   */
  project_image: prismic.ImageField<never>;
  /**
   * Project Banner field in *Project*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: project.project_banner
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/image
   *
   */
  project_banner: prismic.ImageField<never>;
}
/**
 * Item in Project → Content
 *
 */
export interface ProjectDocumentDataContentItem {
  /**
   * Project Headline field in *Project → Content*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: project.content[].project_headline
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  project_headline: prismic.RichTextField;
  /**
   * Project Description field in *Project → Content*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: project.content[].project_description
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  project_description: prismic.RichTextField;
}
/**
 * Project document from Prismic
 *
 * - **API ID**: `project`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ProjectDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<ProjectDocumentData>,
    "project",
    Lang
  >;
/** Content for Social Media documents */
interface SocialMediaDocumentData {
  /**
   * Name field in *Social Media*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: social_media.name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  name: prismic.RichTextField;
  /**
   * Link field in *Social Media*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: social_media.link
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
   *
   */
  link: prismic.LinkField;
}
/**
 * Social Media document from Prismic
 *
 * - **API ID**: `social_media`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SocialMediaDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<SocialMediaDocumentData>,
    "social_media",
    Lang
  >;
/** Content for Works documents */
interface WorksDocumentData {
  /**
   * Slice Zone field in *Works*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: works.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/slices
   *
   */
  slices: prismic.SliceZone<WorksDocumentDataSlicesSlice>;
  /**
   * Meta Description field in *Works*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: works.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  meta_description: prismic.RichTextField;
  /**
   * Meta Image field in *Works*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: works.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/core-concepts/image
   *
   */
  meta_image: prismic.ImageField<never>;
  /**
   * Meta Title field in *Works*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: works.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  meta_title: prismic.KeyTextField;
}
/**
 * Slice for *Works → Slice Zone*
 *
 */
type WorksDocumentDataSlicesSlice = ProjectSlice | HeroWorksSlice;
/**
 * Works document from Prismic
 *
 * - **API ID**: `works`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type WorksDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<WorksDocumentData>, "works", Lang>;
export type AllDocumentTypes =
  | _404Document
  | ContactsDocument
  | HomepageDocument
  | NavigationDocument
  | PageDocument
  | PreloaderDocument
  | ProjectDocument
  | SocialMediaDocument
  | WorksDocument;
/**
 * Primary content in Error → Primary
 *
 */
interface ErrorSliceDefaultPrimary {
  /**
   * Headline field in *Error → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: error.primary.headline
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  headline: prismic.RichTextField;
  /**
   * Description field in *Error → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: error.primary.description
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  description: prismic.RichTextField;
  /**
   * Button Label field in *Error → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: error.primary.button_label
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  button_label: prismic.RichTextField;
  /**
   * Button Link field in *Error → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: error.primary.button_link
   * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
   *
   */
  button_link: prismic.LinkField;
}
/**
 * Default variation for Error Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Default`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type ErrorSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ErrorSliceDefaultPrimary>,
  never
>;
/**
 * Slice variation for *Error*
 *
 */
type ErrorSliceVariation = ErrorSliceDefault;
/**
 * Error Shared Slice
 *
 * - **API ID**: `error`
 * - **Description**: `Error`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type ErrorSlice = prismic.SharedSlice<"error", ErrorSliceVariation>;
/**
 * Primary content in HeroHomepage → Primary
 *
 */
interface HeroHomepageSliceDefaultPrimary {
  /**
   * Headline 1 field in *HeroHomepage → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_homepage.primary.headline_1
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  headline_1: prismic.RichTextField;
  /**
   * Image field in *HeroHomepage → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_homepage.primary.image
   * - **Documentation**: https://prismic.io/docs/core-concepts/image
   *
   */
  image: prismic.ImageField<never>;
  /**
   * Headline 2 field in *HeroHomepage → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_homepage.primary.headline_2
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  headline_2: prismic.RichTextField;
  /**
   * Image 2 field in *HeroHomepage → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_homepage.primary.image_2
   * - **Documentation**: https://prismic.io/docs/core-concepts/image
   *
   */
  image_2: prismic.ImageField<never>;
  /**
   * Image 3 field in *HeroHomepage → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_homepage.primary.image_3
   * - **Documentation**: https://prismic.io/docs/core-concepts/image
   *
   */
  image_3: prismic.ImageField<never>;
  /**
   * Headline 3 field in *HeroHomepage → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_homepage.primary.headline_3
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  headline_3: prismic.RichTextField;
  /**
   * Button Label field in *HeroHomepage → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_homepage.primary.button_label
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  button_label: prismic.RichTextField;
  /**
   * Button Link field in *HeroHomepage → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_homepage.primary.button_link
   * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
   *
   */
  button_link: prismic.LinkField;
  /**
   * Headline 4 field in *HeroHomepage → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_homepage.primary.headline_4
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  headline_4: prismic.RichTextField;
  /**
   * Description field in *HeroHomepage → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_homepage.primary.description
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  description: prismic.RichTextField;
}
/**
 * Default variation for HeroHomepage Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Default`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type HeroHomepageSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroHomepageSliceDefaultPrimary>,
  never
>;
/**
 * Slice variation for *HeroHomepage*
 *
 */
type HeroHomepageSliceVariation = HeroHomepageSliceDefault;
/**
 * HeroHomepage Shared Slice
 *
 * - **API ID**: `hero_homepage`
 * - **Description**: `HeroHomepage`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type HeroHomepageSlice = prismic.SharedSlice<
  "hero_homepage",
  HeroHomepageSliceVariation
>;
/**
 * Primary content in HeroWorks → Primary
 *
 */
interface HeroWorksSliceDefaultPrimary {
  /**
   * Headline field in *HeroWorks → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_works.primary.headline
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  headline: prismic.RichTextField;
  /**
   * Description field in *HeroWorks → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_works.primary.description
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  description: prismic.RichTextField;
  /**
   * Image field in *HeroWorks → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_works.primary.image
   * - **Documentation**: https://prismic.io/docs/core-concepts/image
   *
   */
  image: prismic.ImageField<never>;
}
/**
 * Default variation for HeroWorks Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Default`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type HeroWorksSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroWorksSliceDefaultPrimary>,
  never
>;
/**
 * Slice variation for *HeroWorks*
 *
 */
type HeroWorksSliceVariation = HeroWorksSliceDefault;
/**
 * HeroWorks Shared Slice
 *
 * - **API ID**: `hero_works`
 * - **Description**: `HeroWorks`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type HeroWorksSlice = prismic.SharedSlice<
  "hero_works",
  HeroWorksSliceVariation
>;
/**
 * Primary content in Marquee → Primary
 *
 */
interface MarqueeSliceDefaultPrimary {
  /**
   * Label field in *Marquee → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: marquee.primary.label
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  label: prismic.RichTextField;
  /**
   * Link field in *Marquee → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: marquee.primary.link
   * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
   *
   */
  link: prismic.LinkField;
}
/**
 * Default variation for Marquee Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Default`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type MarqueeSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<MarqueeSliceDefaultPrimary>,
  never
>;
/**
 * Slice variation for *Marquee*
 *
 */
type MarqueeSliceVariation = MarqueeSliceDefault;
/**
 * Marquee Shared Slice
 *
 * - **API ID**: `marquee`
 * - **Description**: `Marquee`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type MarqueeSlice = prismic.SharedSlice<
  "marquee",
  MarqueeSliceVariation
>;
/**
 * Primary content in NavigationItem → Primary
 *
 */
interface NavigationItemSliceDefaultPrimary {
  /**
   * Name field in *NavigationItem → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation_item.primary.name
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  name: prismic.RichTextField;
  /**
   * Link field in *NavigationItem → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation_item.primary.link
   * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
   *
   */
  link: prismic.LinkField;
}
/**
 * Default variation for NavigationItem Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Default`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type NavigationItemSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<NavigationItemSliceDefaultPrimary>,
  never
>;
/**
 * Slice variation for *NavigationItem*
 *
 */
type NavigationItemSliceVariation = NavigationItemSliceDefault;
/**
 * NavigationItem Shared Slice
 *
 * - **API ID**: `navigation_item`
 * - **Description**: `NavigationItem`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type NavigationItemSlice = prismic.SharedSlice<
  "navigation_item",
  NavigationItemSliceVariation
>;
/**
 * Item in NavigationSocialMediaLinks → Items
 *
 */
export interface NavigationSocialMediaLinksSliceDefaultItem {
  /**
   * Social Media field in *NavigationSocialMediaLinks → Items*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation_social_media_links.items[].social_media
   * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
   *
   */
  social_media: prismic.ContentRelationshipField<"social_media" | "contacts">;
}
/**
 * Default variation for NavigationSocialMediaLinks Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Default`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type NavigationSocialMediaLinksSliceDefault =
  prismic.SharedSliceVariation<
    "default",
    Record<string, never>,
    Simplify<NavigationSocialMediaLinksSliceDefaultItem>
  >;
/**
 * Slice variation for *NavigationSocialMediaLinks*
 *
 */
type NavigationSocialMediaLinksSliceVariation =
  NavigationSocialMediaLinksSliceDefault;
/**
 * NavigationSocialMediaLinks Shared Slice
 *
 * - **API ID**: `navigation_social_media_links`
 * - **Description**: `NavigationSocialMediaLinks`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type NavigationSocialMediaLinksSlice = prismic.SharedSlice<
  "navigation_social_media_links",
  NavigationSocialMediaLinksSliceVariation
>;
/**
 * Item in Project → Items
 *
 */
export interface ProjectSliceDefaultItem {
  /**
   * Project field in *Project → Items*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: project.items[].project
   * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
   *
   */
  project: prismic.ContentRelationshipField<"project">;
}
/**
 * Default variation for Project Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Default`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type ProjectSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  Simplify<ProjectSliceDefaultItem>
>;
/**
 * Slice variation for *Project*
 *
 */
type ProjectSliceVariation = ProjectSliceDefault;
/**
 * Project Shared Slice
 *
 * - **API ID**: `project`
 * - **Description**: `Project`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type ProjectSlice = prismic.SharedSlice<
  "project",
  ProjectSliceVariation
>;
/**
 * Primary content in ContentList → Primary
 *
 */
interface ResumeSliceDefaultPrimary {
  /**
   * Image field in *ContentList → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: resume.primary.image
   * - **Documentation**: https://prismic.io/docs/core-concepts/image
   *
   */
  image: prismic.ImageField<never>;
}
/**
 * Item in ContentList → Items
 *
 */
export interface ResumeSliceDefaultItem {
  /**
   * Headline field in *ContentList → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: resume.items[].headline
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  headline: prismic.RichTextField;
  /**
   * Description field in *ContentList → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: resume.items[].description
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  description: prismic.RichTextField;
}
/**
 * Default variation for ContentList Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Default`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type ResumeSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ResumeSliceDefaultPrimary>,
  Simplify<ResumeSliceDefaultItem>
>;
/**
 * Primary content in ContentList → Primary
 *
 */
interface ResumeSliceWithSocialMediaPrimary {
  /**
   * Headline field in *ContentList → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: resume.primary.headline
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  headline: prismic.RichTextField;
}
/**
 * Item in ContentList → Items
 *
 */
export interface ResumeSliceWithSocialMediaItem {
  /**
   * Social Media field in *ContentList → Items*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: resume.items[].social_media
   * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
   *
   */
  social_media: prismic.ContentRelationshipField<"social_media">;
}
/**
 * With Social Media variation for ContentList Slice
 *
 * - **API ID**: `withSocialMedia`
 * - **Description**: `Default`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type ResumeSliceWithSocialMedia = prismic.SharedSliceVariation<
  "withSocialMedia",
  Simplify<ResumeSliceWithSocialMediaPrimary>,
  Simplify<ResumeSliceWithSocialMediaItem>
>;
/**
 * Item in ContentList → Items
 *
 */
export interface ResumeSliceWithEmailAndLocationItem {
  /**
   * Contacts field in *ContentList → Items*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: resume.items[].social_media
   * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
   *
   */
  social_media: prismic.ContentRelationshipField<"contacts">;
}
/**
 * With Email and Location variation for ContentList Slice
 *
 * - **API ID**: `withEmailAndLocation`
 * - **Description**: `Default`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type ResumeSliceWithEmailAndLocation = prismic.SharedSliceVariation<
  "withEmailAndLocation",
  Record<string, never>,
  Simplify<ResumeSliceWithEmailAndLocationItem>
>;
/**
 * Item in ContentList → Items
 *
 */
export interface ResumeSliceProjectsItem {
  /**
   * Project field in *ContentList → Items*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: resume.items[].project
   * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
   *
   */
  project: prismic.ContentRelationshipField<"project">;
}
/**
 * Projects variation for ContentList Slice
 *
 * - **API ID**: `projects`
 * - **Description**: `Default`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type ResumeSliceProjects = prismic.SharedSliceVariation<
  "projects",
  Record<string, never>,
  Simplify<ResumeSliceProjectsItem>
>;
/**
 * Slice variation for *ContentList*
 *
 */
type ResumeSliceVariation =
  | ResumeSliceDefault
  | ResumeSliceWithSocialMedia
  | ResumeSliceWithEmailAndLocation
  | ResumeSliceProjects;
/**
 * ContentList Shared Slice
 *
 * - **API ID**: `resume`
 * - **Description**: `Resume`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type ResumeSlice = prismic.SharedSlice<"resume", ResumeSliceVariation>;
declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig
    ): prismic.Client<AllDocumentTypes>;
  }
  namespace Content {
    export type {
      _404DocumentData,
      _404DocumentDataSlicesSlice,
      _404Document,
      ContactsDocumentData,
      ContactsDocument,
      HomepageDocumentData,
      HomepageDocumentDataSlicesSlice,
      HomepageDocument,
      NavigationDocumentData,
      NavigationDocumentDataSlicesSlice,
      NavigationDocument,
      PageDocumentData,
      PageDocumentDataSlicesSlice,
      PageDocument,
      PreloaderDocumentData,
      PreloaderDocument,
      ProjectDocumentData,
      ProjectDocumentDataContentItem,
      ProjectDocument,
      SocialMediaDocumentData,
      SocialMediaDocument,
      WorksDocumentData,
      WorksDocumentDataSlicesSlice,
      WorksDocument,
      AllDocumentTypes,
      ErrorSliceDefaultPrimary,
      ErrorSliceDefault,
      ErrorSliceVariation,
      ErrorSlice,
      HeroHomepageSliceDefaultPrimary,
      HeroHomepageSliceDefault,
      HeroHomepageSliceVariation,
      HeroHomepageSlice,
      HeroWorksSliceDefaultPrimary,
      HeroWorksSliceDefault,
      HeroWorksSliceVariation,
      HeroWorksSlice,
      MarqueeSliceDefaultPrimary,
      MarqueeSliceDefault,
      MarqueeSliceVariation,
      MarqueeSlice,
      NavigationItemSliceDefaultPrimary,
      NavigationItemSliceDefault,
      NavigationItemSliceVariation,
      NavigationItemSlice,
      NavigationSocialMediaLinksSliceDefaultItem,
      NavigationSocialMediaLinksSliceDefault,
      NavigationSocialMediaLinksSliceVariation,
      NavigationSocialMediaLinksSlice,
      ProjectSliceDefaultItem,
      ProjectSliceDefault,
      ProjectSliceVariation,
      ProjectSlice,
      ResumeSliceDefaultPrimary,
      ResumeSliceDefaultItem,
      ResumeSliceDefault,
      ResumeSliceWithSocialMediaPrimary,
      ResumeSliceWithSocialMediaItem,
      ResumeSliceWithSocialMedia,
      ResumeSliceWithEmailAndLocationItem,
      ResumeSliceWithEmailAndLocation,
      ResumeSliceProjectsItem,
      ResumeSliceProjects,
      ResumeSliceVariation,
      ResumeSlice,
    };
  }
}
