// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  error: dynamic(() => import("./Error")),
  hero_homepage: dynamic(() => import("./HeroHomepage")),
  hero_works: dynamic(() => import("./HeroWorks")),
  marquee: dynamic(() => import("./Marquee")),
  navigation_item: dynamic(() => import("./NavigationItem")),
  navigation_social_media_links: dynamic(() =>
    import("./NavigationSocialMediaLinks")
  ),
  project: dynamic(() => import("./Project")),
  resume: dynamic(() => import("./ContentList")),
};
